//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKU_PLACEMENT_PORTAL
{


    public partial class AdminManageContent
    {

        /// <summary>
        /// placementCountBadge control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl placementCountBadge;

        /// <summary>
        /// GridView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView GridView1;

        /// <summary>
        /// lblNoPlacedStudents control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblNoPlacedStudents;

        /// <summary>
        /// editPlacementId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField editPlacementId;

        /// <summary>
        /// placementImagePreview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image placementImagePreview;

        /// <summary>
        /// placementImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FileUpload placementImage;

        /// <summary>
        /// placementStudentName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox placementStudentName;

        /// <summary>
        /// placementDepartment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList placementDepartment;

        /// <summary>
        /// placementCompanyName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox placementCompanyName;

        /// <summary>
        /// placementYear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList placementYear;

        /// <summary>
        /// placementSubmitBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button placementSubmitBtn;

        /// <summary>
        /// placementCancelBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button placementCancelBtn;

        /// <summary>
        /// galleryCountBadge control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl galleryCountBadge;

        /// <summary>
        /// GridView2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView GridView2;

        /// <summary>
        /// lblNoGallery control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblNoGallery;

        /// <summary>
        /// galleryTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox galleryTitle;

        /// <summary>
        /// galleryImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FileUpload galleryImage;

        /// <summary>
        /// gallerySubmitBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button gallerySubmitBtn;

        /// <summary>
        /// galleryCancelBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button galleryCancelBtn;

        /// <summary>
        /// storyCountBadge control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl storyCountBadge;

        /// <summary>
        /// GridView3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView GridView3;

        /// <summary>
        /// lblNoStories control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblNoStories;

        /// <summary>
        /// storyFormTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl storyFormTitle;

        /// <summary>
        /// editStoryId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField editStoryId;

        /// <summary>
        /// storyStudentName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox storyStudentName;

        /// <summary>
        /// storyDegree control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox storyDegree;

        /// <summary>
        /// storyImagePreview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image storyImagePreview;

        /// <summary>
        /// storyImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FileUpload storyImage;

        /// <summary>
        /// storyRecruiter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox storyRecruiter;

        /// <summary>
        /// storyPackage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox storyPackage;

        /// <summary>
        /// storyRole control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox storyRole;

        /// <summary>
        /// storyQuote control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox storyQuote;

        /// <summary>
        /// storySkills control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox storySkills;

        /// <summary>
        /// storyIsHallOfFame control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox storyIsHallOfFame;

        /// <summary>
        /// storyRank control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList storyRank;

        /// <summary>
        /// storySubmitBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button storySubmitBtn;

        /// <summary>
        /// storyCancelBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button storyCancelBtn;

        /// <summary>
        /// teamCountBadge control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl teamCountBadge;

        /// <summary>
        /// GridViewTeam control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView GridViewTeam;

        /// <summary>
        /// lblNoTeamMembers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNoTeamMembers;

        /// <summary>
        /// teamFormTitle control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl teamFormTitle;

        /// <summary>
        /// teamImagePreview control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image teamImagePreview;

        /// <summary>
        /// teamMemberPhoto control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload teamMemberPhoto;

        /// <summary>
        /// teamMemberName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox teamMemberName;

        /// <summary>
        /// teamMemberRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox teamMemberRole;

        /// <summary>
        /// teamMemberDesc control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox teamMemberDesc;

        /// <summary>
        /// teamMemberMobile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox teamMemberMobile;

        /// <summary>
        /// teamMemberEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox teamMemberEmail;

        /// <summary>
        /// teamSubmitBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button teamSubmitBtn;

        /// <summary>
        /// teamCancelBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button teamCancelBtn;
    }
}
