//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKU_PLACEMENT_PORTAL
{
    public partial class CompanyManageDrives
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl drivesSubtitle;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl drivesCountBadge;
        protected global::System.Web.UI.WebControls.GridView GridView1;
        protected global::System.Web.UI.WebControls.TextBox cmpDriveRole;
        protected global::System.Web.UI.WebControls.TextBox cmpDrivePackage;
        protected global::System.Web.UI.WebControls.TextBox cmpDriveMinCgpa;
        protected global::System.Web.UI.WebControls.TextBox cmpDriveVacancies;
        protected global::System.Web.UI.WebControls.TextBox cmpDriveDate;
        protected global::System.Web.UI.WebControls.DropDownList cmpDriveStatus;
        protected global::System.Web.UI.WebControls.TextBox cmpDriveLocation;
        protected global::System.Web.UI.WebControls.TextBox cmpDriveDescription;
        protected global::System.Web.UI.WebControls.Button cmpBtnResetDrive;
        protected global::System.Web.UI.WebControls.Button cmpBtnSubmitDrive;
    }
}
